version: 0.2

phases:
  install:
    commands:
      - echo Installing dependency...
      - npm i
  build:
    commands:
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  discard-paths: no 
  base-directory: dist